### ISSUE TITLE
Line numbers are wrong after multiline GHC_OPTIONS

### ISSUE THREAD

**Issue by ndmitchell** [haskell-suite/haskell-src-exts#218]
Given:

    {-# OPTIONS_GHC
        -a
        -a
        -a
        -a
        -a
        -a
        -a
        -a
        -a
        -a
        -a #-}
    main :: IO ()
    main = data

This raises a parse error about `data` on line 3 - seemingly any newlines inside GHC_OPTIONS don't count for additional lines. From https://github.com/ndmitchell/hlint/issues/126

**Comment by ikirill** [comment]
Could the issue be that `parseFile` gives the `OptionsPragma` as a string that contains newlines which might prevent the parser from seeing those newlines? If I insert a multiline `LANGUAGE` pragma, it returns a list of `Ident` instead, suggesting that's why multiline language pragmas don't cause problems.
