### ISSUE TITLE
Top level declaration is parsed as a PatBind

### ISSUE THREAD

**Issue by mpickering** [haskell-suite/haskell-src-exts#241]
If a function has a single clause and no arguments it is parsed as a `PatBind` rather than a `FunBind`. There should be no variable PatBind's at the top level. 

A simple example

```
foo = 5
```

Output
```
Parse result of typetest.hs:
Module () Nothing [] [] [PatBind () (PVar () (Ident () "foo")) (UnGuardedRhs () (Lit () (Int () 5 "5"))) Nothing]
```

GHC Output

```

({ typetest.hs:1:1 }
 Just (Ann (DP (0,0)) [] [] [((G AnnEofPos),DP (1,0))] Nothing Nothing)
 (HsModule 
  (Nothing) 
  (Nothing) 
  [] 
  [
   ({ typetest.hs:1:1-7 }
    Just (Ann (DP (0,0)) [] [] [] Nothing Nothing)
    (ValD 
     (FunBind 
      ({ typetest.hs:1:1-3 }
       Just (Ann (DP (0,0)) [] [] [((G AnnVal),DP (0,0))] Nothing Nothing)
       (Unqual {OccName: foo})) 
      (False) 
      (MG 
       [
        ({ typetest.hs:1:1-7 }
         Just (Ann (DP (0,0)) [] [] [((G AnnEqual),DP (0,1))] Nothing Nothing)
         (Match 
          (Just 
           ((,) 
            ({ typetest.hs:1:1-3 }
             Just (Ann (DP (0,0)) [] [] [((G AnnVal),DP (0,0))] Nothing Nothing)
             (Unqual {OccName: foo})) 
            (False))) 
          [] 
          (Nothing) 
          (GRHSs 
           [
            ({ typetest.hs:1:5-7 }
             Just (Ann (DP (0,-1)) [] [] [] Nothing Nothing)
             (GRHS 
              [] 
              ({ typetest.hs:1:7 }
               Just (Ann (DP (0,1)) [] [] [((G AnnVal),DP (0,0))] Nothing Nothing)
               (HsOverLit {HsOverLit:5}))))] 
           (EmptyLocalBinds))))] 
       [] 
       (PlaceHolder) 
       (FromSource)) 
      (WpHole) 
      (PlaceHolder) 
      [])))] 
  (Nothing) 
  (Nothing)))
```

**Comment by ndmitchell** [comment]
It's not how GHC treats them, but do you have any compelling reason this is wrong? Eg the Haskell report? It seems in this instance FunBind and PatBind are both allowable. Surely x:xs = [1..] must be a top level PatBind?

**Comment by mpickering** [comment]
You're right, the [report](https://www.haskell.org/onlinereport/haskell2010/haskellch4.html#x10-620004) states that

> Either binding may appear at the top-level of a module or within a where or let construct.

There is a [note](http://haskell.inf.elte.hu/docs/7.11.20150722.noWin32/html/libraries/ghc-7.11.20150722/HsBinds.html#t:HsBindLR) in the GHC AST which describes that a `PatBind` should never be a variable which is where I based this ticket on. 

I guess it depends whether the goal of `haskell-src-exts` is to mirror the GHC parser as far as possible or not. For my purposes I would argue that it should exactly mirror the GHC parser but in some places it already deviates  - one example is applying fixity resolution. Another is that `haskell-src-exts` checks to make sure that all `FunBind`s have a consistent arity which is something the GHC parser doesn't do. 

A less intrusive fix would be to remove the arity check as well which should cause most programs to behave in exactly the same manner as before with the bonus of more closely matching the GHC parser.

**Comment by ndmitchell** [comment]
I don't think matching GHC is a goal at all, it's all about the Haskell report. Of course, we want to parse everything GHC can, but that's a bit different. 

Thinking about it, I suspect you are right that the arity check does not belong in the parser.

**Comment by pjonsson** [comment]
Mirroring the GHC parser isn't a goal in itself if you ask me. Parsing things that GHC parse is interesting though. Fixity resolution isn't perfect in HSE as we all know.

What is the conclusion on this, that we're following the standard? We could move out everything from the parser in principle, but why do we want to remove the arity checking from the parser right now? I don't have anything offhand but there could be something inside HSE that relies on that invariant.

**Comment by mpickering** [comment]
GHC's parser doesn't perform an arity check, this step is only performed later which means that GHC accepts programs where functions have inconsistent arity. Further, the arity check in HSE isn't complete as the following program parses correctly.

```
foo = baz
foo x = baz
```

The first is parsed as a PatBind and the second as a FunBind. HLint has relied on this behaviour for it's templating mechanism for quite a while. Removing the arity check allows the fragment to continue to be parsed with the other suggested change.

Whilst it appears that both GHC and HSE follow the standard, I don't think it makes sense to diverge where the standard is ambiguous.

**Comment by ndmitchell** [comment]
While the standard does say things about consistent arity, it's a check after parsing, not in the BNF. In the same way HSE does not check for duplicate names or type errors, so to have only the arity check is a little curious.

**Comment by ndmitchell** [comment]
For PatBind vs FunBind they are both fine, so I'm not sure I'd do anything about that side - better stay the same than gratuitous change.

**Comment by pjonsson** [comment]
I think this boils down to the interpretation of how much checking parsing entails and the role of HSE. What do we want? We all agree that type checking is definitely not parsing and even if we could build a type checker there are many usages of HSE that would not need or even want typechecking, HLint probably being one of them. I'm not a fan of introducing phase distinctions if that means all client code has to change from `parse file` into `arityCheck $ parse file` and there are no reasonable usages of `parse file`.

The fact that arity checking is not complete is a bug with the arity checking implementation in HSE rather than an argument for not having it there at all. If fixing that bug makes the implementation horrendously complex one should consider whether it's worth fixing the bug and/or consider scrapping the functionality completely.

I don't understand the comment about relying on the behaviour for the templating mechanism in HLint. Do you want more checking? Less checking?

Neil, is your life simplified if we move the arity checking out of the default parsing in HSE? Would you turn that functionality off if you could?

**Comment by ndmitchell** [comment]
I already half-disable fixity resolution in HLint, so yes, I'd probably disable arity analysis if I could. It doesn't add anything to HLint, and it means a few things won't work when they otherwise would. In particular, if you don't fully resolve CPP, then you can get issues with:

    #ifdef FOO
    bar x = x
    #else
    bar y z = y z
    #endif

At the moment you don't give errors for duplicate names in pattern variables, which is a check you could reasonably add, but I'd argue shouldn't because it isn't parse related. My concern about the arity analysis is that it requires name analysis (knowing too things are the same) which is something HSE otherwise avoids.

My guess is that the people who do want arity analysis probably also want name analysis, and thus are doing a lot of work already, and this is barely any additional work.

**Comment by ndmitchell** [comment]
Also note that there is a sensible (albeit complex) semantics for functions with different arities, so it seems a reasonable thing that a Haskell compiler might one day add anyway.

**Comment by pjonsson** [comment]
Ok. Let's not change PatBind/FunBind behaviour since we're following the standard. I buy the CPP-argument but I'm hesitant to wipe the check and change the default behaviour of HSE without any retreat right now.

@mpickering: would you care to add a parameter that enables/disables the arity checking and stick it into the ParseMonad somewhere? That gives Neil the ability to disable the checking and other users will not get smacked in the face if they are relying on the functionality.

**Comment by pjonsson** [comment]
Our treatment of PatBind/FunBind is legal so we'll leave that as it is. The arity checking patch by Matthew is merged so users can turn it off. Closing the ticket since the underlying issue seems taken care of.
