### ISSUE TITLE
Pretty-printer adds an unnecessary semicolon

### ISSUE THREAD

**Issue by 23Skidoo** [haskell-suite/haskell-src-exts#309]
Consider the following GHCi session:

```
Prelude> import Language.Haskell.Exts
Prelude Language.Haskell.Exts> let prettyPrintInLine = prettyPrintWithMode (defaultMode { layout = PPInLine })
Prelude Language.Haskell.Exts> let ParseOk x = parseDecl "h x = f (filter ('a' ==) x)"
Prelude Language.Haskell.Exts> prettyPrintInLine x
"h x = f (filter ('a' ==) x);"
```

As you can see, `prettyPrintInLine` adds an unnecessary semicolon to the output for some reason. Originally reported [here](https://github.com/23Skidoo/pointful/issues/9) and [here](https://github.com/lambdabot/lambdabot/issues/144).

**Comment by mpickering** [comment]
I can still reproduce this with 1.18, thanks for the report.

**Comment by klangner** [comment]
It looks that this problem is only presented when the **layout == PPInLine**.

Because of this I can't add test case using example files (This test will pass).

IMHO the best option to add this test case would be to test for property:

> Everything pretty printed from any AST should be parsed into the same AST. No matter what mode was used during pretty printing.


I can add this property (with minimal generator enough for this problem) to the test groups and then try to fix this bug.
It will be similar to the _extensionProperties_.

What do you think about it?

**Comment by mpickering** [comment]
I don't think other pretty printing layout styles are used very often and I suspect that many of tests will be broken if you start testing them all!

It would be sufficient in this case to verify yourself that the fix works without a test.
