### ISSUE TITLE
Making SrcLoc/SrcSpan fields strict introduces performance regression

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-suite/haskell-src-exts#340]
Commit https://github.com/haskell-suite/haskell-src-exts/commit/a388dde3a223219a9e911bdb2edf9d8cce054bdb (introduced in `haskell-src-exts-1.19`) seems to have brought about a rather serious performance regression. I noticed this because recent `lens` Travis builds would lag for 10 minutes when running `hlint` tests, causing those Travis builds to eventually die. (See https://github.com/ekmett/lens/issues/693 for the issue that was migrated here.)

To recap https://github.com/ekmett/lens/issues/693, here is the timing for the `lens` `hlint` tests when `hlint` is built against `haskell-src-exts-1.18.2`:

```
$ time ./dist/build/hlint/hlint
real    0m1.771s
user    0m4.872s
sys     0m0.936s
```

And when built against `haskell-src-exts-1.19`:

```
$ time ./dist/build/hlint/hlint
real    0m35.408s
user    1m40.216s
sys     0m28.264s
```

(Weirdly, on my machine it takes well under 10 minutes to complete, but I might have better hardware than most Travis buildbots. Either way, the second times are much longer.)

Reverting https://github.com/haskell-suite/haskell-src-exts/commit/a388dde3a223219a9e911bdb2edf9d8cce054bdb was sufficient to restore the `hlint` test time back to its original state, as noted in https://github.com/ekmett/lens/issues/693#issuecomment-263355505.

**Comment by RyanGlScott** [comment]
@mpickering: I compiled the test suite with `--enable-profiling --ghc-options=-fprof-auto`, and I have profiling reports for when it was built against [`haskell-src-exts-1.18.2`](https://gist.githubusercontent.com/RyanGlScott/93ae1e66b0badd31aa8d10eb72729a89/raw/eedc649ea5e02b7940747a38f9e0fe5eced0c51a/hlint-hse-1.18.2.prof) and [`haskell-src-exts-1.19`](https://gist.githubusercontent.com/RyanGlScott/10a97a00a325775a4f63bbfad78f8054/raw/a471dd1956413082fd69e5ad90278d170b05371f/hlint-hse-1.19.prof) (warning: large files). I also have heap profiles, if that information would be helpful.

**Comment by mpickering** [comment]
Do you still have these profiling reports?

**Comment by RyanGlScott** [comment]
* [`hlint-1.18.2.ps`](https://gist.githubusercontent.com/RyanGlScott/f36a6c66737e3a5fe9a57a736820be3c/raw/3a022bab3afd2106386a3eee8169456d8072cd04/hlint-hse-1.18.2.ps)
* [`hlint-1.19.ps`](https://gist.githubusercontent.com/RyanGlScott/f36a6c66737e3a5fe9a57a736820be3c/raw/3a022bab3afd2106386a3eee8169456d8072cd04/hlint-hse-1.19.ps)

**Comment by mpickering** [comment]
Thanks, I did a new release.

**Comment by ndmitchell** [comment]
Sorry I'm late to the party - I only just saw this ticket - and only went looking for it when I got a performance regression in HLint on my laptop, which happened to `cabal update` at just the right point.

The cause is in Uniplate, which maintains a "fast" hit table of which types occur in which other types. To build this hit table it needs to be able to use the `Data.Data` API to construct values of a given type knowing only the type. For types with strict fields that doesn't work, so it uses a slow-path which is quite a lot slower. I'm going to make some modifications:

* HLint, check for the perf regression, so if it recurrs I'll find out first: https://github.com/ndmitchell/hlint/issues/297
* Uniplate, allow strict fields if you give the library a hint: https://github.com/ndmitchell/uniplate/issues/21
