### ISSUE TITLE
Out of memory when building on GHC 8.2.1

### ISSUE THREAD

**Issue by YoEight** [haskell-suite/haskell-src-exts#374]
Greetings.

I have a lib which has a transient dependency on `haskell-src-exts`. I also have a travis [build][] that consistently fails building `haskell-src-exts` with an *out of memory* as described below:

```
--  While building package haskell-src-exts-1.19.1 using:
      /home/travis/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.0.0.2_ghc-8.2.1 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.0.0.2 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure (-9) (THIS MAY INDICATE OUT OF MEMORY)
    Logs have been written to: /home/travis/build/YoEight/eventstore/.stack-work/logs/haskell-src-exts-1.19.1.log
```

GHC: 8.2.1
stack: 1.5.1

This build use `stack` with default argument.

Regards

[build]: https://travis-ci.org/YoEight/eventstore/jobs/262985472

**Comment by mpickering** [comment]
I can't reproduce this and it doesn't seem to cause anyone else problems.

**Comment by brandon-leapyear** [comment]
:sparkles: _**This is an old work account. Please reference @brandonchinn178 for all future communication**_ :sparkles:


---

I'm getting this error consistently in Circle CI. I also don't know what you mean by "it doesn't seem to cause anyone else problems", because it's been an issue before:

* https://github.com/haskell-suite/haskell-src-exts/issues/239
* https://github.com/haskell-suite/haskell-src-exts/issues/80

Luckily, my company has the premium account with Circle CI so I can beef up the VM running the build, but this has bit me in my personal projects before. I think there should be at least some documentation somewhere for this issue, so that developers at least know that this is a known issue with `haskell-src-exts` (namely, that it takes a lot of memory to build).
